---
title: "Weissman-replication-raw-processed"
author: "Marton Kovacs"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

# Load packages

```{r load packages}
library(tidyverse)
library(janitor)
library(purrrlyr)
library(osfr)
library(lubridate)
```

# Load helper functions

```{r load helper functions}
source("utils.R")
```

# Download data from OSF
## OSF auth (until project is public)
osf_auth(token = read_lines("osf_token_write_martonbalazskovacs.txt"))
```{r osf authentication}
```

## Connect to data OSF folder
```{r osf connect to OSF folder}
data_guid <- "9knds"

weissman_project <- osf_retrieve_node(data_guid)
```

## Download data locally

```{r osf download data}
local_data_pth <- file.path("data","Source")

create_local_structure(local_data_pth)

data_files <- 
  weissman_project %>% 
  osf_ls_files() %>% 
  filter(name == "Source") %>% 
  osf_ls_files() 

data_files %>% 
  group_by(name) %>% # for each experiment type
  do(download_files(.,local_data_pth))

# uncomment following line to remove the data   
# remove_local_data(local_data_pth)
```

# Import data

```{r}
# Saving subfolder names
subfolder <- list("primeprobe", "flanker", "stroop", "simon")

# Reading in data
raw <-
  tibble(task = subfolder,
         response = map(subfolder,
                       ~ read_plus(subfolder_name = .x,
                                   pattern = ".tsv$",
                                   path = "data/Raw/",
                                   sep = "\t")))
```

# Calculate accuracy in each task for each participant

```{r}
raw <-
  raw %>%
  mutate(test = map(response,
                    ~ mutate(., correct = case_when(responseTarget == responseContent ~ 1L,
                                                    responseTarget != responseContent ~ 0L))),
         test = map(test,
                     . %>% 
                      filter(isPractice == 0L) %>% 
                      group_by(participant_id, id) %>% 
                      mutate(prop = sum(correct) / n() * 100,
                             drop = case_when(prop < 70 ~ 1L,
                                              TRUE ~ 0L))))
# TODO: filter excludes practice trials from the dataframe. rewrite the function to keep them
```

# Save task to individual dataframes

```{r}
primeprobe_raw <- raw %>% filter(task == "primeprobe") %>% select(response) %>% unnest()

flanker_raw <- raw %>% filter(task == "flanker") %>% select(response) %>% unnest()

stroop_raw <- raw %>% filter(task == "stroop") %>% select(response) %>% unnest()

simon_raw <- raw %>% filter(task == "simon") %>% select(response) %>% unnest()
```

# Calucalte the response time variable
```{r}

```
