---
title: "Weissman-replication-source-raw"
author: "Marton Kovacs"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

# Load packages
```{r load packages}
library(tidyverse)
library(glue)
library(janitor)
library(osfr)
```

# Load helper functions

```{r load helper functions}
source("utils.R")
```

# Download data from OSF
## OSF auth (until project is public)
osf_auth(token = read_lines("osf_token_write_martonbalazskovacs.txt"))
```{r osf authentication}
```

## Connect to data OSF folder
```{r osf connect to OSF folder}
data_guid <- "9knds"

weissman_project <- osf_retrieve_node(data_guid)
```

## Download data locally

```{r osf download data}
local_data_pth <- file.path("data","Source")

create_local_structure(local_data_pth)

data_files <- 
  weissman_project %>% 
  osf_ls_files() %>% 
  filter(name == "Source") %>% 
  osf_ls_files() 

data_files %>% 
  group_by(name) %>% # for each experiment type
  do(download_files(.,local_data_pth))

# uncomment following line to remove the data   
# remove_local_data(local_data_pth)
```

# Import and merge data

```{r}
## Function to save subdirectories and filename as a variable
read_plus <- function(pattern = ".csv$", path = "data/Source/", subfolder_name = subfolder_name, exclude = exclude) {
  list.files(path = paste0(path, subfolder_name), pattern = pattern, full.names = T, recursive = T) %>% 
    .[ !grepl(exclude, .) ] %>% 
    map_dfr(.,
        ~ read_csv(.x) %>% 
          mutate(data_type = str_extract(.x, "(?<=/).*?(?=/)"),
                 filename = str_remove_all(.x, ".*/|.csv"),
                 task = str_extract(.x, subfolder_name)))
}

# Saving subfolder names
subfolder <- list("primeprobe", "flanker", "stroop", "simon")

# Read in response datafiles
source <-
  tibble(task = subfolder,
         response = map2(subfolder, "demographics.csv$",
                       ~ read_plus(subfolder_name = .x,
                                   exclude = .y)),
         demographics = map2(subfolder, "2019",
                       ~ read_plus(subfolder_name = .x,
                                  exclude = .y)))

source$response[[1]] %>% View()
```

# Join demographic data with responses

```{r}

```