---
title: "Weissman-replication-alternate-figures"
author: "Matt Jaquiery"
date: "14/12/2019"
output: html_document
---

```{r load packages, warning = FALSE, message = FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, osfr, lme4, BayesFactor, DescTools, sjstats, car, broom, papaja, cowplot)
```

# Load helper functions

```{r load helper functions}
source("utils.R")
```

# Import data

Ensure you have the data downloaded by running the data analysis script or manually downloading from the [OSF repository](https://osf.io/9knds/).

```{r, message = FALSE, warning = FALSE}
# Saving subfolder names
subfolder <- list("primeprobe", "flanker", "stroop", "simon")

# Reading data
processed <-
  tibble(task = subfolder,
         rt_data = map(subfolder,
                       ~ read_plus(subfolder_name = .x,
                                   pattern = ".tsv$",
                                   path = "data/Processed_main/", #change to Processed_main or whichever else parameter you set in the preprocessing script
                                   sep = "\t",
                                   include = "_Rt_")),
         acc_data = map(subfolder,
                        ~ read_plus(subfolder_name = .x,
                                    pattern = ".tsv$",
                                    path = "data/Processed_main/", #change to Processed_main or whichever else parameter you set in the preprocessing script
                                    sep = "\t",
                                    include = "_Acc_")))
```

# Summarise data

Because ggplot's stat_summary has the bizarre behaviour of dropping out-of-axis values _before_ calculating the summary, we will do the calculations manually here.

```{r}
processed <-
  processed %>% 
  mutate(cse_plot_rt_data = map(rt_data,
                                . %>% 
                                  mutate(isPrevCongruent = case_when(isPrevCongruent ==  0L ~ "Incongruent",
                                                                     isPrevCongruent ==  1L ~ "Congruent"),
                                         isCongruent = case_when(isCongruent ==  0L ~ "Incongruent",
                                                                 isCongruent ==  1L ~ "Congruent")) %>%
                                  group_by(participant_id, isPrevCongruent, isCongruent) %>% 
                                  summarise(N = n(),
                                            mean_rt = mean(rt, na.rm = T)) %>%
                                  group_by(isPrevCongruent, isCongruent) %>% 
                                  # We can get the below in a clever way using nesting, but this is simpler even 
                                  # though it calls mean_cl_normal 3 times
                                  summarise(N = n(),
                                            ci_high = mean_cl_normal(mean_rt)$ymax,
                                            ci_low = mean_cl_normal(mean_rt)$ymin, 
                                            mean_rt = mean_cl_normal(mean_rt)$y)
                                ),
         cse_plot_acc_data = map(acc_data,
                                . %>% 
                                  mutate(isPrevCongruent = case_when(isPrevCongruent ==  0L ~ "Incongruent",
                                                                     isPrevCongruent ==  1L ~ "Congruent"),
                                         isCongruent = case_when(isCongruent ==  0L ~ "Incongruent",
                                                                 isCongruent ==  1L ~ "Congruent")) %>%
                                  group_by(participant_id, isPrevCongruent, isCongruent) %>% 
                                  summarise(N = n(),
                                            mean_acc = mean(isCorrect, na.rm = T)) %>%
                                  group_by(isPrevCongruent, isCongruent) %>% 
                                  summarise(N = n(),
                                            ci_high = mean_cl_normal(mean_acc)$ymax,
                                            ci_low = mean_cl_normal(mean_acc)$ymin, 
                                            mean_acc = mean_cl_normal(mean_acc)$y)
                                )
         )
```

# Figures

```{r}
# Approximate APA style
theme_set(
  theme_light() +
    theme(
      panel.grid = element_blank(),
      rect = element_blank(),
      strip.background = element_blank(),
      strip.text = element_text(colour = 'black'),
      text = element_text(size = 14),
      axis.line = element_line(size = 1, colour = 'black'),
      axis.ticks = element_line(size = 1, colour = 'black')
    )
)

```

## RT

```{r}
processed$task[[1]] <- "Prime-probe task"
processed$task[[2]] <- "Flanker task"
processed$task[[3]] <- "Stroop task"
processed$task[[4]] <- "Simon task"

processed %>% 
  select(cse_plot_rt_data, task) %>% 
  unnest(c(cse_plot_rt_data, task)) %>% 
  ggplot() +
  aes(x = isPrevCongruent, 
      y = mean_rt, 
      ymax = ci_high,
      ymin = ci_low,
      shape = isCongruent, 
      group = isCongruent) +
  geom_point(position = position_dodge(width = .5), size = 3) +
  geom_errorbar(position = position_dodge(width = .5), width = 0) +
  geom_line(position = position_dodge(.5)) + 
  facet_grid(. ~ str_to_title(task)) + 
  scale_shape_manual(values = c(4, 16)) +
  # scale_y_continuous(limits = c(600, 900)) +
  scale_x_discrete(expand = c(.5, 0)) +
  #ggtitle("Mean response times by condition") +
  xlab("Congruency of the previous trial") +
  ylab("Response time +/- 95% CI") +
  guides(shape = guide_legend(title = "Congruency of \n the current trial")) 

ggsave("figures/weissman_replication_rt_cse_alt.png", 
       width = 14.4, height = 8, plot = last_plot())
```

## Accuracy

```{r}
processed$task[[1]] <- "Prime-probe task"
processed$task[[2]] <- "Flanker task"
processed$task[[3]] <- "Stroop task"
processed$task[[4]] <- "Simon task"

processed %>% 
  select(cse_plot_acc_data, task) %>% 
  unnest(c(cse_plot_acc_data, task)) %>% 
  ggplot() +
  aes(x = isPrevCongruent, 
      y = mean_acc, 
      ymax = ci_high,
      ymin = ci_low,
      shape = isCongruent, 
      group = isCongruent) +
  geom_point(position = position_dodge(width = .5), size = 3) +
  geom_errorbar(position = position_dodge(width = .5), width = 0) +
  geom_line(position = position_dodge(.5)) + 
  facet_grid(. ~ str_to_title(task)) + 
  scale_shape_manual(values = c(4, 16)) +
  scale_y_continuous(limits = c(0.92, 1)) +
  scale_x_discrete(expand = c(.5, 0)) +
  #ggtitle("Mean accuracy by condition") +
  xlab("Congruency of the previous trial") +
  ylab("Accuracy +/- 95% CI") +
  guides(shape = guide_legend(title = "Congruency of \n the current trial")) 

ggsave("figures/weissman_replication_acc_cse_alt.png", 
       width = 14.4, height = 8, plot = last_plot())
```
